import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { uid } from '../data';

// ═══════════════════════════════════════════
// TaskBoard — 角色任務管理板
// ═══════════════════════════════════════════

const ACCENT = '#0e7490';
const STORAGE_KEY = 'hcmc_tasks';

const ROLE_COLORS = {
  '醫師': '#2563eb',
  '護士': '#059669',
  '前台': '#d97706',
  '管理員': '#7c3aed',
};

const ROLES = ['醫師', '護士', '前台', '管理員'];

const PRIORITY_MAP = {
  high: { label: '緊急', color: '#ef4444', bg: '#fef2f2', border: '#ef4444' },
  normal: { label: '一般', color: '#f59e0b', bg: '#fffbeb', border: '#f59e0b' },
  low: { label: '低', color: '#3b82f6', bg: '#eff6ff', border: '#3b82f6' },
};

const LINKED_PAGES = [
  { id: '', label: '（無）' },
  { id: 'dash', label: 'Dashboard' },
  { id: 'rev', label: '營業紀錄' },
  { id: 'exp', label: '開支紀錄' },
  { id: 'booking', label: '預約系統' },
  { id: 'queue', label: '掛號排隊' },
  { id: 'emr', label: '電子病歷' },
  { id: 'inventory', label: '藥材庫存' },
  { id: 'billing', label: '配藥/收費' },
  { id: 'closing', label: '日結對賬' },
  { id: 'monthend', label: '月結作業' },
  { id: 'payroll', label: '計糧' },
  { id: 'pay', label: '糧單' },
  { id: 'stocktake', label: '藥物盤點' },
  { id: 'crm', label: 'WhatsApp CRM' },
  { id: 'patient', label: '病人管理' },
  { id: 'followup', label: '覆診管理' },
  { id: 'pnl', label: '損益表' },
  { id: 'mpf', label: '強積金' },
  { id: 'report', label: '報表中心' },
  { id: 'dispensing', label: '開藥日誌' },
  { id: 'formulas', label: '我的處方' },
  { id: 'vitals', label: '健康資訊' },
];

const today = () => new Date().toISOString().substring(0, 10);
const tomorrow = () => {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().substring(0, 10);
};
const dayOfMonth = () => new Date().getDate();
const dayOfWeek = () => new Date().getDay(); // 0=Sun,1=Mon,...

function formatDate(d) {
  if (!d) return '';
  const parts = d.split('-');
  if (parts.length !== 3) return d;
  return `${parts[1]}/${parts[2]}`;
}

function formatDateFull(d) {
  if (!d) return '';
  const weekdays = ['日', '一', '二', '三', '四', '五', '六'];
  const dt = new Date(d + 'T00:00:00');
  return `${dt.getFullYear()}年${dt.getMonth() + 1}月${dt.getDate()}日 (星期${weekdays[dt.getDay()]})`;
}

function daysFromToday(d) {
  if (!d) return 0;
  const t = new Date(today() + 'T00:00:00');
  const dd = new Date(d + 'T00:00:00');
  return Math.round((dd - t) / (1000 * 60 * 60 * 24));
}

// ── Default settings ──
const DEFAULT_SETTINGS = {
  rentDueDay: 15,
  mpfDueDay: 20,
  payrollDueDay: 5,
  socialMediaDay: 1, // Monday
  // Payment schedule: array of recurring monthly payments
  paymentSchedule: [
    { id: 'rent_pk', label: '太子租金', day: 2, amount: 0, category: '租金', store: '太子', active: true },
    { id: 'rent_sht', label: '宋皇臺租金', day: 3, amount: 0, category: '租金', store: '宋皇臺', active: true },
    { id: 'pay_hui', label: '許醫師人工', day: 4, amount: 0, category: '人工', role: '醫師', staff: '許醫師', active: true },
    { id: 'pay_tsang', label: '曾醫師人工', day: 5, amount: 0, category: '人工', role: '醫師', staff: '曾醫師', active: true },
    { id: 'pay_zoe', label: 'Zoe 趙穎欣人工', day: 6, amount: 0, category: '人工', role: '職員', staff: 'Zoe 趙穎欣', active: true },
    { id: 'pay_kelly', label: 'Kelly 人工', day: 7, amount: 0, category: '人工', role: '職員', staff: 'Kelly', active: true },
  ],
};

// ── Load / Save ──
function loadTasks() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      return { tasks: parsed.tasks || [], settings: { ...DEFAULT_SETTINGS, ...parsed.settings } };
    }
  } catch { /* ignore */ }
  return { tasks: [], settings: { ...DEFAULT_SETTINGS } };
}

function saveTasks(data) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}

// ── Auto Task Generation ──
function generateAutoTasks(existingTasks, data, settings) {
  const td = today();
  const tom = tomorrow();
  const dom = dayOfMonth();
  const dow = dayOfWeek();
  const newTasks = [];

  const exists = (key) => existingTasks.some(t => t.autoKey === key);
  const makeTask = (title, role, priority, autoKey, linkedPage, dueDate, dueTime) => ({
    id: uid(),
    title,
    description: '',
    dueDate: dueDate || td,
    dueTime: dueTime || null,
    priority: priority || 'normal',
    role,
    status: 'pending',
    completedAt: null,
    completedBy: null,
    recurring: 'daily',
    linkedPage: linkedPage || null,
    autoGenerated: true,
    autoKey,
    createdAt: new Date().toISOString(),
  });

  // Count data
  const todayBookings = (data.bookings || []).filter(b => b.date === td && b.status !== 'cancelled');
  const tomorrowBookings = (data.bookings || []).filter(b => b.date === tom && b.status !== 'cancelled');
  const bookingCount = todayBookings.length;
  const tomorrowCount = tomorrowBookings.length;
  const lowStockItems = (data.inventory || []).filter(i => {
    const qty = Number(i.qty || i.quantity || 0);
    const min = Number(i.minQty || i.min || i.reorderLevel || 10);
    return qty <= min;
  });
  const hasFollowUps = (data.consultations || []).some(c => {
    const fu = c.followUp || c.followUpDate;
    return fu && fu === td;
  });
  const pendingBills = (data.revenue || []).filter(r => r.status === 'unpaid' || r.status === 'pending');

  // ── 醫師 Doctor Tasks ──
  const dk = (key) => `doctor_${key}_${td}`;
  if (!exists(dk('bookings'))) {
    newTasks.push(makeTask(`查看今日預約 (${bookingCount} 位病人)`, '醫師', 'high', dk('bookings'), 'booking', td, '09:00'));
  }
  if (!exists(dk('followup')) && hasFollowUps) {
    newTasks.push(makeTask('覆診提醒跟進', '醫師', 'high', dk('followup'), 'followup', td, '09:30'));
  }
  if (!exists(dk('rxcheck'))) {
    newTasks.push(makeTask('處方藥物檢查', '醫師', 'normal', dk('rxcheck'), 'formulas', td, '10:00'));
  }
  if (!exists(dk('emrsign'))) {
    newTasks.push(makeTask('簽署病歷記錄', '醫師', 'normal', dk('emrsign'), 'emr', td, '18:00'));
  }

  // ── 護士 Nurse Tasks ──
  const nk = (key) => `nurse_${key}_${td}`;
  if (!exists(nk('prep'))) {
    newTasks.push(makeTask('開診準備：檢查診療室物資', '護士', 'high', nk('prep'), null, td, '08:30'));
  }
  if (!exists(nk('bookings'))) {
    newTasks.push(makeTask(`確認今日預約名單 (${bookingCount} 位)`, '護士', 'high', nk('bookings'), 'booking', td, '08:45'));
  }
  if (!exists(nk('vitals'))) {
    newTasks.push(makeTask('量度等候病人生命體徵', '護士', 'normal', nk('vitals'), 'vitals', td, '09:00'));
  }
  if (!exists(nk('stockcheck')) && lowStockItems.length > 0) {
    newTasks.push(makeTask(`藥材庫存檢查 (${lowStockItems.length} 項低庫存)`, '護士', 'high', nk('stockcheck'), 'inventory', td, '11:00'));
  } else if (!exists(nk('stockcheck'))) {
    newTasks.push(makeTask('藥材庫存檢查', '護士', 'normal', nk('stockcheck'), 'inventory', td, '11:00'));
  }
  if (!exists(nk('disinfect'))) {
    newTasks.push(makeTask('消毒診療室', '護士', 'normal', nk('disinfect'), null, td, '18:30'));
  }

  // ── 前台 Reception Tasks ──
  const rk = (key) => `reception_${key}_${td}`;
  if (!exists(rk('tomorrow'))) {
    newTasks.push(makeTask(`確認明日預約 (${tomorrowCount} 位) — 致電提醒`, '前台', 'high', rk('tomorrow'), 'booking', td, '15:00'));
  }
  if (!exists(rk('closing'))) {
    newTasks.push(makeTask('處理今日收銀結算', '前台', 'normal', rk('closing'), 'closing', td, '18:00'));
  }
  if (!exists(rk('unpaid'))) {
    const unpaidCount = pendingBills.length;
    newTasks.push(makeTask(`檢查未付帳單${unpaidCount > 0 ? ` (${unpaidCount} 張)` : ''}`, '前台', unpaidCount > 0 ? 'high' : 'normal', rk('unpaid'), 'arap', td, '16:00'));
  }
  if (!exists(rk('inquiries'))) {
    newTasks.push(makeTask('回覆查詢訊息', '前台', 'normal', rk('inquiries'), 'crm', td, '10:00'));
  }

  // ── 管理員 Admin Tasks ──
  const ak = (key) => `admin_${key}_${td}`;

  // Daily
  if (!exists(ak('revenue'))) {
    newTasks.push(makeTask('查看今日營業額', '管理員', 'normal', ak('revenue'), 'rev', td, '18:00'));
  }

  // Monthly: Day 1-5
  if (dom >= 1 && dom <= 5) {
    const mk = (key) => `admin_${key}_${td.substring(0, 7)}`;
    if (!exists(mk('pnl'))) {
      newTasks.push({
        ...makeTask('完成上月 P&L 損益表', '管理員', 'high', mk('pnl'), 'monthend', td, null),
        recurring: 'monthly',
      });
    }
    if (!exists(mk('payroll'))) {
      newTasks.push({
        ...makeTask('計糧 + 出糧單', '管理員', 'high', mk('payroll'), 'payroll', td, null),
        recurring: 'monthly',
      });
    }
  }
  if (dom === 1) {
    const mk = (key) => `admin_${key}_${td.substring(0, 7)}`;
    if (!exists(mk('stocktake'))) {
      newTasks.push({
        ...makeTask('庫存盤點', '管理員', 'normal', mk('stocktake'), 'stocktake', td, null),
        recurring: 'monthly',
      });
    }
  }
  if (dom === settings.rentDueDay) {
    const mk = (key) => `admin_${key}_${td.substring(0, 7)}`;
    if (!exists(mk('rent'))) {
      newTasks.push({
        ...makeTask('交租提醒', '管理員', 'high', mk('rent'), 'exp', td, null),
        recurring: 'monthly',
      });
    }
  }
  if (dom === settings.mpfDueDay) {
    const mk = (key) => `admin_${key}_${td.substring(0, 7)}`;
    if (!exists(mk('mpf'))) {
      newTasks.push({
        ...makeTask('MPF 供款提醒', '管理員', 'high', mk('mpf'), 'mpf', td, null),
        recurring: 'monthly',
      });
    }
  }

  // Weekly
  if (dow === 1) { // Monday
    const wk = `admin_social_${td}`;
    if (!exists(wk)) {
      newTasks.push({
        ...makeTask('發佈本週社交媒體內容', '管理員', 'normal', wk, null, td, null),
        recurring: 'weekly',
      });
    }
  }
  if (dow === 5) { // Friday
    const wk = `admin_weeklyreview_${td}`;
    if (!exists(wk)) {
      newTasks.push({
        ...makeTask('檢視本週業績報告', '管理員', 'normal', wk, 'report', td, null),
        recurring: 'weekly',
      });
    }
  }

  // ── 付款排程 Payment Schedule ──
  const schedule = settings.paymentSchedule || [];
  schedule.filter(s => s.active).forEach(s => {
    if (dom === s.day) {
      const pk = `payment_${s.id}_${td.substring(0, 7)}`;
      if (!exists(pk)) {
        const amtLabel = s.amount ? ` HK$${s.amount.toLocaleString()}` : '';
        newTasks.push({
          ...makeTask(`💳 ${s.label}${amtLabel}`, '管理員', 'high', pk, s.category === '人工' ? 'payroll' : 'exp', td, null),
          recurring: 'monthly',
          description: `分類：${s.category}${s.store ? ' | 分店：' + s.store : ''}${s.staff ? ' | 對象：' + s.staff : ''}`,
        });
      }
    }
  });

  return newTasks;
}

// ── Mark overdue ──
function markOverdue(tasks) {
  const td = today();
  return tasks.map(t => {
    if (t.status === 'pending' && t.dueDate < td) {
      return { ...t, status: 'overdue' };
    }
    return t;
  });
}

// ── Seed data for realistic demo ──
function generateSeedData() {
  const td = '2026-03-02';
  const yesterday = '2026-03-01';

  return [
    // Doctor auto tasks
    { id: uid(), title: '查看今日預約 (8 位病人)', description: '', dueDate: td, dueTime: '09:00', priority: 'high', role: '醫師', status: 'completed', completedAt: '2026-03-02T09:15:00.000Z', completedBy: '醫師A', recurring: 'daily', linkedPage: 'booking', autoGenerated: true, autoKey: `doctor_bookings_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '覆診提醒跟進', description: '陳大文、李美玲需覆診', dueDate: td, dueTime: '09:30', priority: 'high', role: '醫師', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'followup', autoGenerated: true, autoKey: `doctor_followup_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '處方藥物檢查', description: '', dueDate: td, dueTime: '10:00', priority: 'normal', role: '醫師', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'formulas', autoGenerated: true, autoKey: `doctor_rxcheck_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '簽署病歷記錄', description: '', dueDate: td, dueTime: '18:00', priority: 'normal', role: '醫師', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'emr', autoGenerated: true, autoKey: `doctor_emrsign_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },

    // Nurse auto tasks
    { id: uid(), title: '開診準備：檢查診療室物資', description: '', dueDate: td, dueTime: '08:30', priority: 'high', role: '護士', status: 'completed', completedAt: '2026-03-02T08:35:00.000Z', completedBy: '護士A', recurring: 'daily', linkedPage: null, autoGenerated: true, autoKey: `nurse_prep_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '確認今日預約名單 (8 位)', description: '', dueDate: td, dueTime: '08:45', priority: 'high', role: '護士', status: 'completed', completedAt: '2026-03-02T08:50:00.000Z', completedBy: '護士A', recurring: 'daily', linkedPage: 'booking', autoGenerated: true, autoKey: `nurse_bookings_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '量度等候病人生命體徵', description: '', dueDate: td, dueTime: '09:00', priority: 'normal', role: '護士', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'vitals', autoGenerated: true, autoKey: `nurse_vitals_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '藥材庫存檢查 (3 項低庫存)', description: '當歸、黃芪、甘草低於安全庫存', dueDate: td, dueTime: '11:00', priority: 'high', role: '護士', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'inventory', autoGenerated: true, autoKey: `nurse_stockcheck_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '消毒診療室', description: '', dueDate: td, dueTime: '18:30', priority: 'normal', role: '護士', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: null, autoGenerated: true, autoKey: `nurse_disinfect_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },

    // Reception auto tasks
    { id: uid(), title: '確認明日預約 (5 位) — 致電提醒', description: '', dueDate: td, dueTime: '15:00', priority: 'high', role: '前台', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'booking', autoGenerated: true, autoKey: `reception_tomorrow_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '處理今日收銀結算', description: '', dueDate: td, dueTime: '18:00', priority: 'normal', role: '前台', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'closing', autoGenerated: true, autoKey: `reception_closing_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '檢查未付帳單 (2 張)', description: '', dueDate: td, dueTime: '16:00', priority: 'high', role: '前台', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'arap', autoGenerated: true, autoKey: `reception_unpaid_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '回覆查詢訊息', description: '', dueDate: td, dueTime: '10:00', priority: 'normal', role: '前台', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'crm', autoGenerated: true, autoKey: `reception_inquiries_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },

    // Admin auto tasks (March 2 = Day 2, Monday)
    { id: uid(), title: '查看今日營業額', description: '', dueDate: td, dueTime: '18:00', priority: 'normal', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: 'daily', linkedPage: 'rev', autoGenerated: true, autoKey: `admin_revenue_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '完成上月 P&L 損益表', description: '二月份損益表', dueDate: td, dueTime: null, priority: 'high', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: 'monthly', linkedPage: 'monthend', autoGenerated: true, autoKey: 'admin_pnl_2026-03', createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '計糧 + 出糧單', description: '三月份薪金', dueDate: td, dueTime: null, priority: 'high', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: 'monthly', linkedPage: 'payroll', autoGenerated: true, autoKey: 'admin_payroll_2026-03', createdAt: '2026-03-02T08:00:00.000Z' },
    { id: uid(), title: '庫存盤點', description: '三月份盤點', dueDate: '2026-03-01', dueTime: null, priority: 'normal', role: '管理員', status: 'overdue', completedAt: null, completedBy: null, recurring: 'monthly', linkedPage: 'stocktake', autoGenerated: true, autoKey: 'admin_stocktake_2026-03', createdAt: '2026-03-01T08:00:00.000Z' },
    { id: uid(), title: '發佈本週社交媒體內容', description: '本週主題：春季養生', dueDate: td, dueTime: null, priority: 'normal', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: 'weekly', linkedPage: null, autoGenerated: true, autoKey: `admin_social_${td}`, createdAt: '2026-03-02T08:00:00.000Z' },

    // Manual tasks
    { id: uid(), title: '訂購新一批艾灸條', description: '聯絡供應商確認價格', dueDate: td, dueTime: null, priority: 'normal', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: 'purchase', autoGenerated: false, autoKey: null, createdAt: '2026-02-28T10:00:00.000Z' },
    { id: uid(), title: '更新診所 Instagram 頁面', description: '上傳上週活動照片', dueDate: td, dueTime: null, priority: 'low', role: '前台', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: null, autoGenerated: false, autoKey: null, createdAt: '2026-02-28T14:00:00.000Z' },
    { id: uid(), title: '整理病歷文件夾', description: '2025年病歷歸檔', dueDate: '2026-03-05', dueTime: null, priority: 'low', role: '護士', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: null, autoGenerated: false, autoKey: null, createdAt: '2026-02-27T09:00:00.000Z' },
    { id: uid(), title: '聯絡維修公司檢查冷氣', description: '二號診療室冷氣漏水', dueDate: '2026-03-03', dueTime: null, priority: 'high', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: null, autoGenerated: false, autoKey: null, createdAt: '2026-02-28T16:00:00.000Z' },

    // Yesterday overdue
    { id: uid(), title: '跟進長者醫療券申請', description: '王伯伯醫療券', dueDate: yesterday, dueTime: null, priority: 'high', role: '前台', status: 'overdue', completedAt: null, completedBy: null, recurring: null, linkedPage: 'voucher', autoGenerated: false, autoKey: null, createdAt: '2026-02-28T09:00:00.000Z' },

    // Upcoming
    { id: uid(), title: '安排員工急救培訓', description: '聯絡紅十字會', dueDate: '2026-03-07', dueTime: null, priority: 'normal', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: 'training', autoGenerated: false, autoKey: null, createdAt: '2026-02-25T10:00:00.000Z' },
    { id: uid(), title: '準備三月推廣活動', description: '春季養生講座', dueDate: '2026-03-08', dueTime: null, priority: 'normal', role: '管理員', status: 'pending', completedAt: null, completedBy: null, recurring: null, linkedPage: 'promo', autoGenerated: false, autoKey: null, createdAt: '2026-02-20T10:00:00.000Z' },
  ];
}

// ── Styles ──
const S = {
  container: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '0 8px 80px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  topBar: {
    background: '#fff',
    borderRadius: 14,
    boxShadow: '0 2px 12px rgba(0,0,0,0.07)',
    padding: '16px 20px',
    marginBottom: 16,
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  dateTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#1e293b',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  stats: {
    display: 'flex',
    gap: 16,
    fontSize: 14,
    color: '#64748b',
    flexWrap: 'wrap',
  },
  statItem: (color) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontWeight: 600,
    color,
  }),
  tabs: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  tab: (active) => ({
    padding: '6px 16px',
    borderRadius: 20,
    border: 'none',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: active ? 700 : 500,
    background: active ? ACCENT : '#f1f5f9',
    color: active ? '#fff' : '#475569',
    transition: 'all 0.2s',
  }),
  addBtn: {
    padding: '8px 18px',
    borderRadius: 20,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 700,
    background: ACCENT,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    whiteSpace: 'nowrap',
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: (color) => ({
    fontSize: 15,
    fontWeight: 700,
    color: color || '#1e293b',
    marginBottom: 8,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    cursor: 'pointer',
    userSelect: 'none',
  }),
  card: (priority, isCompleted, isOverdue) => ({
    background: isOverdue ? '#fef2f2' : '#fff',
    borderRadius: 12,
    boxShadow: '0 1px 6px rgba(0,0,0,0.06)',
    padding: '14px 16px',
    marginBottom: 8,
    borderLeft: `4px solid ${PRIORITY_MAP[priority]?.border || '#e2e8f0'}`,
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    opacity: isCompleted ? 0.55 : 1,
    transition: 'all 0.3s ease',
    position: 'relative',
  }),
  checkbox: (checked) => ({
    width: 22,
    height: 22,
    borderRadius: 6,
    border: `2px solid ${checked ? ACCENT : '#cbd5e1'}`,
    background: checked ? ACCENT : '#fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 2,
    transition: 'all 0.2s',
  }),
  taskTitle: (completed) => ({
    fontSize: 15,
    fontWeight: 600,
    color: completed ? '#94a3b8' : '#1e293b',
    textDecoration: completed ? 'line-through' : 'none',
    cursor: 'pointer',
    lineHeight: 1.4,
  }),
  taskMeta: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 4,
    alignItems: 'center',
  },
  badge: (bg, color) => ({
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 10,
    background: bg,
    color,
    whiteSpace: 'nowrap',
  }),
  dueLabel: (overdue) => ({
    fontSize: 12,
    color: overdue ? '#ef4444' : '#64748b',
    fontWeight: overdue ? 600 : 400,
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  }),
  linkBtn: {
    fontSize: 11,
    color: ACCENT,
    cursor: 'pointer',
    textDecoration: 'underline',
    border: 'none',
    background: 'none',
    padding: 0,
    fontWeight: 600,
  },
  modal: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999,
    padding: 16,
  },
  modalContent: {
    background: '#fff',
    borderRadius: 16,
    padding: '24px 28px',
    width: '100%',
    maxWidth: 500,
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: 20,
  },
  formGroup: {
    marginBottom: 16,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: '#475569',
    marginBottom: 4,
    display: 'block',
  },
  formInput: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 10,
    border: '1.5px solid #e2e8f0',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  formSelect: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 10,
    border: '1.5px solid #e2e8f0',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
    background: '#fff',
    cursor: 'pointer',
  },
  formRow: {
    display: 'flex',
    gap: 12,
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 24,
  },
  btnOutline: {
    padding: '10px 22px',
    borderRadius: 10,
    border: '1.5px solid #e2e8f0',
    background: '#fff',
    color: '#475569',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnPrimary: {
    padding: '10px 22px',
    borderRadius: 10,
    border: 'none',
    background: ACCENT,
    color: '#fff',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  },
  bell: {
    position: 'relative',
    cursor: 'pointer',
    fontSize: 22,
    lineHeight: 1,
    padding: 6,
  },
  bellBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: '50%',
    background: '#ef4444',
    color: '#fff',
    fontSize: 10,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellDropdown: {
    position: 'absolute',
    top: 40,
    right: 0,
    width: 340,
    maxHeight: 400,
    overflowY: 'auto',
    background: '#fff',
    borderRadius: 14,
    boxShadow: '0 8px 30px rgba(0,0,0,0.15)',
    zIndex: 100,
    padding: '12px 0',
  },
  bellItem: {
    padding: '10px 16px',
    borderBottom: '1px solid #f1f5f9',
    cursor: 'pointer',
    fontSize: 13,
    color: '#334155',
    display: 'flex',
    gap: 8,
    alignItems: 'flex-start',
    transition: 'background 0.15s',
  },
  emptyState: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#94a3b8',
    fontSize: 15,
  },
  deleteBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    color: '#cbd5e1',
    padding: '2px 6px',
    borderRadius: 4,
    transition: 'color 0.2s',
  },
};

// ── Main Component ──
export default function TaskBoard({ showToast, data, user, setPage }) {
  const [store, setStore] = useState(() => loadTasks());
  const [roleFilter, setRoleFilter] = useState('全部');
  const [showModal, setShowModal] = useState(false);
  const [showBell, setShowBell] = useState(false);
  const [showCompleted, setShowCompleted] = useState(false);
  const [editTask, setEditTask] = useState(null);
  const bellRef = useRef(null);
  const onNavigate = setPage; // alias for consistency

  // ── Init: seed data if empty, generate auto tasks, mark overdue ──
  useEffect(() => {
    let { tasks, settings } = store;
    let changed = false;

    // Seed if empty
    if (tasks.length === 0) {
      tasks = generateSeedData();
      changed = true;
    }

    // Mark overdue
    const updated = markOverdue(tasks);
    if (JSON.stringify(updated) !== JSON.stringify(tasks)) {
      tasks = updated;
      changed = true;
    }

    // Auto-generate
    const newAuto = generateAutoTasks(tasks, data || {}, settings);
    if (newAuto.length > 0) {
      tasks = [...tasks, ...newAuto];
      changed = true;
    }

    // ── Auto-complete payment tasks by matching expenses ──
    const thisMonth = today().substring(0, 7);
    const monthExpenses = (data?.expenses || []).filter(e => (e.date || '').startsWith(thisMonth));
    const monthRevenue = (data?.revenue || []).filter(e => (e.date || '').startsWith(thisMonth));
    const allFinancial = [...monthExpenses, ...monthRevenue];
    const paySchedule = settings.paymentSchedule || [];

    tasks = tasks.map(t => {
      if (t.status !== 'pending' && t.status !== 'overdue') return t;
      if (!t.autoKey || !t.autoKey.startsWith('payment_')) return t;
      // Find matching schedule item
      const schedId = t.autoKey.split('_')[1] + '_' + t.autoKey.split('_')[2]; // e.g. "rent_pk"
      const schedItem = paySchedule.find(s => t.autoKey.includes(s.id));
      if (!schedItem) return t;
      // Match: any expense this month with similar merchant/desc containing the schedule label or staff name
      const matchKeywords = [schedItem.label, schedItem.staff, schedItem.store].filter(Boolean).map(k => k.toLowerCase());
      const hasMatch = allFinancial.some(exp => {
        const searchText = [exp.merchant, exp.desc, exp.name, exp.item, exp.note].filter(Boolean).join(' ').toLowerCase();
        return matchKeywords.some(k => k && searchText.includes(k));
      });
      if (hasMatch) {
        changed = true;
        return { ...t, status: 'completed', completedAt: new Date().toISOString(), completedBy: 'TG AI 自動配對' };
      }
      return t;
    });

    if (changed) {
      const newStore = { tasks, settings };
      setStore(newStore);
      saveTasks(newStore);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Save on store changes ──
  const saveStore = useCallback((newStore) => {
    setStore(newStore);
    saveTasks(newStore);
  }, []);

  // ── Toggle task completion ──
  const toggleTask = useCallback((taskId) => {
    setStore(prev => {
      const tasks = prev.tasks.map(t => {
        if (t.id !== taskId) return t;
        if (t.status === 'completed') {
          // Uncomplete
          return { ...t, status: t.dueDate < today() ? 'overdue' : 'pending', completedAt: null, completedBy: null };
        }
        // Complete
        return { ...t, status: 'completed', completedAt: new Date().toISOString(), completedBy: user?.name || '使用者' };
      });
      const newStore = { ...prev, tasks };
      saveTasks(newStore);
      return newStore;
    });
    if (showToast) showToast('任務狀態已更新');
  }, [user, showToast]);

  // ── Delete task ──
  const deleteTask = useCallback((taskId) => {
    setStore(prev => {
      const tasks = prev.tasks.filter(t => t.id !== taskId);
      const newStore = { ...prev, tasks };
      saveTasks(newStore);
      return newStore;
    });
    if (showToast) showToast('已刪除任務');
  }, [showToast]);

  // ── Add / Edit task ──
  const saveTask = useCallback((task) => {
    setStore(prev => {
      let tasks;
      if (editTask) {
        tasks = prev.tasks.map(t => t.id === task.id ? task : t);
      } else {
        tasks = [...prev.tasks, task];
      }
      const newStore = { ...prev, tasks };
      saveTasks(newStore);
      return newStore;
    });
    if (showToast) showToast(editTask ? '已更新任務' : '已新增任務');
    setShowModal(false);
    setEditTask(null);
  }, [editTask, showToast]);

  // ── Close bell on outside click ──
  useEffect(() => {
    if (!showBell) return;
    const handler = (e) => {
      if (bellRef.current && !bellRef.current.contains(e.target)) setShowBell(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [showBell]);

  // ── Filtered tasks ──
  const filteredTasks = useMemo(() => {
    if (roleFilter === '全部') return store.tasks;
    return store.tasks.filter(t => t.role === roleFilter);
  }, [store.tasks, roleFilter]);

  // ── Categorize ──
  const { overdue, todayPending, completedToday, upcoming } = useMemo(() => {
    const td = today();
    const next7 = [];
    for (let i = 1; i <= 7; i++) {
      const d = new Date();
      d.setDate(d.getDate() + i);
      next7.push(d.toISOString().substring(0, 10));
    }

    const overdue = filteredTasks.filter(t => t.status === 'overdue');
    const todayPending = filteredTasks.filter(t => t.status === 'pending' && t.dueDate === td)
      .sort((a, b) => (a.dueTime || '99:99').localeCompare(b.dueTime || '99:99'));
    const completedToday = filteredTasks.filter(t => t.status === 'completed' && t.dueDate === td);
    const upcoming = filteredTasks.filter(t => t.status === 'pending' && next7.includes(t.dueDate))
      .sort((a, b) => a.dueDate.localeCompare(b.dueDate) || (a.dueTime || '').localeCompare(b.dueTime || ''));

    return { overdue, todayPending, completedToday, upcoming };
  }, [filteredTasks]);

  // ── Stats ──
  const allTodayPending = useMemo(() => store.tasks.filter(t => t.status === 'pending' && t.dueDate === today()), [store.tasks]);
  const allOverdue = useMemo(() => store.tasks.filter(t => t.status === 'overdue'), [store.tasks]);
  const allCompleted = useMemo(() => store.tasks.filter(t => t.status === 'completed' && t.dueDate === today()), [store.tasks]);
  const bellCount = allOverdue.length + allTodayPending.length;

  // ── Notification bell items ──
  const bellItems = useMemo(() => {
    return [...allOverdue, ...allTodayPending]
      .sort((a, b) => {
        if (a.status === 'overdue' && b.status !== 'overdue') return -1;
        if (b.status === 'overdue' && a.status !== 'overdue') return 1;
        return (a.priority === 'high' ? 0 : 1) - (b.priority === 'high' ? 0 : 1);
      })
      .slice(0, 15);
  }, [allOverdue, allTodayPending]);

  // ── Task Card ──
  const TaskCard = ({ task }) => {
    const p = PRIORITY_MAP[task.priority] || PRIORITY_MAP.normal;
    const rc = ROLE_COLORS[task.role] || '#64748b';
    const isCompleted = task.status === 'completed';
    const isOverdue = task.status === 'overdue';
    const diff = daysFromToday(task.dueDate);
    const linkedLabel = LINKED_PAGES.find(lp => lp.id === task.linkedPage)?.label;

    return (
      <div style={S.card(task.priority, isCompleted, isOverdue)}>
        <div
          style={S.checkbox(isCompleted)}
          onClick={() => toggleTask(task.id)}
          role="checkbox"
          aria-checked={isCompleted}
          aria-label={`標記 ${task.title} 為${isCompleted ? '未完成' : '已完成'}`}
          tabIndex={0}
          onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleTask(task.id); } }}
        >
          {isCompleted && (
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path d="M3 7L6 10L11 4" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </div>

        <div style={{ flex: 1, minWidth: 0 }}>
          <div
            style={S.taskTitle(isCompleted)}
            onClick={() => {
              if (task.linkedPage && onNavigate) onNavigate(task.linkedPage);
            }}
            title={task.linkedPage ? `前往 ${linkedLabel || task.linkedPage}` : ''}
          >
            {task.title}
          </div>

          {task.description && (
            <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 2, lineHeight: 1.3 }}>{task.description}</div>
          )}

          <div style={S.taskMeta}>
            <span style={S.badge(p.bg, p.color)}>
              {task.priority === 'high' ? '\u{1F534}' : task.priority === 'low' ? '\u{1F535}' : '\u{1F7E1}'} {p.label}
            </span>
            <span style={S.badge(rc + '18', rc)}>{task.role}</span>

            {task.dueTime && (
              <span style={S.dueLabel(isOverdue)}>{task.dueTime}</span>
            )}

            {diff !== 0 && !isCompleted && (
              <span style={S.dueLabel(isOverdue)}>
                {isOverdue ? `逾期 ${Math.abs(diff)} 日` : diff > 0 ? `${diff} 日後` : ''}
              </span>
            )}

            {task.linkedPage && onNavigate && (
              <button
                style={S.linkBtn}
                onClick={(e) => { e.stopPropagation(); onNavigate(task.linkedPage); }}
              >
                {linkedLabel || task.linkedPage} &rarr;
              </button>
            )}

            {task.autoGenerated && (
              <span style={{ fontSize: 10, color: '#94a3b8', fontStyle: 'italic' }}>自動</span>
            )}

            {isCompleted && task.completedBy && (
              <span style={{ fontSize: 11, color: '#94a3b8' }}>
                {task.completedBy} 完成
              </span>
            )}
          </div>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: 4, flexShrink: 0, alignItems: 'center' }}>
          {!task.autoGenerated && (
            <button
              style={{ ...S.deleteBtn, position: 'static', color: '#94a3b8' }}
              title="編輯"
              onClick={() => { setEditTask(task); setShowModal(true); }}
            >
              &#9998;
            </button>
          )}
          <button
            style={{ ...S.deleteBtn, position: 'static' }}
            title="刪除"
            onClick={() => deleteTask(task.id)}
            onMouseEnter={e => e.target.style.color = '#ef4444'}
            onMouseLeave={e => e.target.style.color = '#cbd5e1'}
          >
            &times;
          </button>
        </div>
      </div>
    );
  };

  // ── Section component ──
  const Section = ({ icon, title, color, tasks, collapsible, defaultOpen = true }) => {
    const [open, setOpen] = useState(defaultOpen);
    if (tasks.length === 0) return null;

    return (
      <div style={S.section}>
        <div style={S.sectionHeader(color)} onClick={() => collapsible && setOpen(!open)}>
          <span>{icon}</span>
          <span>{title} ({tasks.length})</span>
          {collapsible && <span style={{ fontSize: 12, color: '#94a3b8' }}>{open ? '\u25B2' : '\u25BC'}</span>}
        </div>
        {open && tasks.map(t => <TaskCard key={t.id} task={t} />)}
      </div>
    );
  };

  return (
    <div style={S.container}>
      {/* ── Top Bar ── */}
      <div style={S.topBar}>
        <div style={S.topRow}>
          <div style={S.dateTitle}>
            <span style={{ fontSize: 24 }}>{'\u{1F4CB}'}</span>
            <div>
              <div>任務板</div>
              <div style={{ fontSize: 13, fontWeight: 400, color: '#64748b' }}>{formatDateFull(today())}</div>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={S.stats}>
              <span style={S.statItem('#f59e0b')}>{allTodayPending.length} 待辦</span>
              <span style={S.statItem('#16a34a')}>{allCompleted.length} 已完成</span>
              <span style={S.statItem('#ef4444')}>{allOverdue.length} 逾期</span>
            </div>

            {/* Notification Bell */}
            <div ref={bellRef} style={{ position: 'relative' }}>
              <div
                style={S.bell}
                onClick={() => setShowBell(!showBell)}
                role="button"
                aria-label={`通知 (${bellCount} 項)`}
                tabIndex={0}
                onKeyDown={e => { if (e.key === 'Enter') setShowBell(!showBell); }}
              >
                {'\u{1F514}'}
                {bellCount > 0 && <div style={S.bellBadge}>{bellCount > 99 ? '99+' : bellCount}</div>}
              </div>

              {showBell && (
                <div style={S.bellDropdown}>
                  <div style={{ padding: '4px 16px 10px', fontWeight: 700, fontSize: 14, color: '#1e293b', borderBottom: '1px solid #f1f5f9' }}>
                    待處理任務 ({bellCount})
                  </div>
                  {bellItems.length === 0 && (
                    <div style={{ padding: '20px 16px', textAlign: 'center', color: '#94a3b8', fontSize: 13 }}>暫無待辦事項</div>
                  )}
                  {bellItems.map(t => (
                    <div
                      key={t.id}
                      style={S.bellItem}
                      onClick={() => {
                        if (t.linkedPage && onNavigate) onNavigate(t.linkedPage);
                        setShowBell(false);
                      }}
                      onMouseEnter={e => e.currentTarget.style.background = '#f8fafc'}
                      onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                    >
                      <span style={{ fontSize: 10, marginTop: 2 }}>
                        {t.status === 'overdue' ? '\u{1F534}' : t.priority === 'high' ? '\u{1F7E1}' : '\u{1F535}'}
                      </span>
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontWeight: 600, fontSize: 13 }}>{t.title}</div>
                        <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 2 }}>
                          {t.role} {t.dueTime ? `| ${t.dueTime}` : ''} {t.status === 'overdue' ? `| 逾期 ${Math.abs(daysFromToday(t.dueDate))} 日` : ''}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <button
              style={S.addBtn}
              onClick={() => { setEditTask(null); setShowModal(true); }}
            >
              + 新增任務
            </button>
          </div>
        </div>

        {/* Role Tabs */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
          <div style={S.tabs}>
            {['全部', ...ROLES].map(r => (
              <button
                key={r}
                style={{
                  ...S.tab(roleFilter === r),
                  ...(r !== '全部' && roleFilter === r ? { background: ROLE_COLORS[r] } : {}),
                }}
                onClick={() => setRoleFilter(r)}
              >
                {r}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* ── Task Sections ── */}
      <Section icon={'\u{1F534}'} title="逾期" color="#ef4444" tasks={overdue} />
      <Section icon={'\u{1F7E1}'} title="今日待辦" color="#f59e0b" tasks={todayPending} />
      <Section icon={'\u2705'} title="已完成" color="#16a34a" tasks={completedToday} collapsible defaultOpen={false} />
      <Section icon={'\u{1F4C5}'} title="即將到期" color="#64748b" tasks={upcoming} collapsible defaultOpen />

      {/* Empty state */}
      {overdue.length === 0 && todayPending.length === 0 && completedToday.length === 0 && upcoming.length === 0 && (
        <div style={S.emptyState}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>{'\u{1F389}'}</div>
          <div style={{ fontSize: 16, fontWeight: 600, color: '#475569' }}>
            {roleFilter === '全部' ? '暫無任務' : `${roleFilter} 暫無任務`}
          </div>
          <div style={{ marginTop: 4 }}>點擊「新增任務」建立新的待辦事項</div>
        </div>
      )}

      {/* ── 付款排程 Section ── */}
      <PaymentSchedule settings={store.settings} onSave={(newSettings) => {
        setStore(prev => {
          const updated = { ...prev, settings: { ...prev.settings, ...newSettings } };
          saveTasks(updated);
          return updated;
        });
        if (showToast) showToast('付款排程已更新');
      }} />

      {/* ── New Task Modal ── */}
      {showModal && (
        <TaskModal
          task={editTask}
          onSave={saveTask}
          onClose={() => { setShowModal(false); setEditTask(null); }}
        />
      )}
    </div>
  );
}

// ── Task Modal ──
function TaskModal({ task, onSave, onClose }) {
  const isEdit = !!task;
  const [title, setTitle] = useState(task?.title || '');
  const [description, setDescription] = useState(task?.description || '');
  const [dueDate, setDueDate] = useState(task?.dueDate || today());
  const [dueTime, setDueTime] = useState(task?.dueTime || '');
  const [priority, setPriority] = useState(task?.priority || 'normal');
  const [role, setRole] = useState(task?.role || '醫師');
  const [recurring, setRecurring] = useState(task?.recurring || '');
  const [linkedPage, setLinkedPage] = useState(task?.linkedPage || '');
  const modalRef = useRef(null);

  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!title.trim()) return;

    const saved = {
      id: task?.id || uid(),
      title: title.trim(),
      description: description.trim(),
      dueDate,
      dueTime: dueTime || null,
      priority,
      role,
      status: task?.status || 'pending',
      completedAt: task?.completedAt || null,
      completedBy: task?.completedBy || null,
      recurring: recurring || null,
      linkedPage: linkedPage || null,
      autoGenerated: task?.autoGenerated || false,
      autoKey: task?.autoKey || null,
      createdAt: task?.createdAt || new Date().toISOString(),
    };
    onSave(saved);
  };

  return (
    <div style={S.modal} onClick={onClose}>
      <div style={S.modalContent} onClick={e => e.stopPropagation()} ref={modalRef}>
        <div style={S.modalTitle}>{isEdit ? '編輯任務' : '新增任務'}</div>
        <form onSubmit={handleSubmit}>
          <div style={S.formGroup}>
            <label style={S.formLabel}>任務名稱 *</label>
            <input
              style={S.formInput}
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="輸入任務名稱..."
              autoFocus
              required
              onFocus={e => e.target.style.borderColor = ACCENT}
              onBlur={e => e.target.style.borderColor = '#e2e8f0'}
            />
          </div>

          <div style={S.formGroup}>
            <label style={S.formLabel}>描述</label>
            <textarea
              style={{ ...S.formInput, minHeight: 70, resize: 'vertical' }}
              value={description}
              onChange={e => setDescription(e.target.value)}
              placeholder="詳細描述（可選）"
              onFocus={e => e.target.style.borderColor = ACCENT}
              onBlur={e => e.target.style.borderColor = '#e2e8f0'}
            />
          </div>

          <div style={S.formRow}>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>到期日</label>
              <input
                type="date"
                style={S.formInput}
                value={dueDate}
                onChange={e => setDueDate(e.target.value)}
              />
            </div>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>時間</label>
              <input
                type="time"
                style={S.formInput}
                value={dueTime}
                onChange={e => setDueTime(e.target.value)}
              />
            </div>
          </div>

          <div style={S.formRow}>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>優先級</label>
              <select style={S.formSelect} value={priority} onChange={e => setPriority(e.target.value)}>
                <option value="high">緊急</option>
                <option value="normal">一般</option>
                <option value="low">低</option>
              </select>
            </div>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>負責角色</label>
              <select style={S.formSelect} value={role} onChange={e => setRole(e.target.value)}>
                {ROLES.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
            </div>
          </div>

          <div style={S.formRow}>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>重複</label>
              <select style={S.formSelect} value={recurring} onChange={e => setRecurring(e.target.value)}>
                <option value="">無</option>
                <option value="daily">每日</option>
                <option value="weekly">每週</option>
                <option value="monthly">每月</option>
              </select>
            </div>
            <div style={{ ...S.formGroup, flex: 1 }}>
              <label style={S.formLabel}>連結頁面</label>
              <select style={S.formSelect} value={linkedPage} onChange={e => setLinkedPage(e.target.value)}>
                {LINKED_PAGES.map(lp => <option key={lp.id} value={lp.id}>{lp.label}</option>)}
              </select>
            </div>
          </div>

          <div style={S.modalActions}>
            <button type="button" style={S.btnOutline} onClick={onClose}>取消</button>
            <button type="submit" style={S.btnPrimary}>{isEdit ? '儲存' : '新增'}</button>
          </div>
        </form>
      </div>
    </div>
  );
}

// ── Payment Schedule Sub-Component ──
function PaymentSchedule({ settings, onSave }) {
  const [open, setOpen] = useState(false);
  const [schedule, setSchedule] = useState(settings.paymentSchedule || []);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ label: '', day: 1, amount: 0, category: '租金', store: '', staff: '', active: true });

  const categories = ['租金', '管理費', '人工', '保險', 'MPF', '水費', '電費', '電話/網絡', '藥材/耗材', '其他'];

  const startEdit = (item) => {
    setEditing(item.id);
    setForm({ ...item });
  };

  const saveItem = () => {
    let updated;
    if (editing && schedule.some(s => s.id === editing)) {
      updated = schedule.map(s => s.id === editing ? { ...form, id: editing } : s);
    } else {
      const id = 'ps_' + Date.now().toString(36);
      updated = [...schedule, { ...form, id }];
    }
    setSchedule(updated);
    onSave({ paymentSchedule: updated });
    setEditing(null);
    setForm({ label: '', day: 1, amount: 0, category: '租金', store: '', staff: '', active: true });
  };

  const deleteItem = (id) => {
    const updated = schedule.filter(s => s.id !== id);
    setSchedule(updated);
    onSave({ paymentSchedule: updated });
  };

  const toggleActive = (id) => {
    const updated = schedule.map(s => s.id === id ? { ...s, active: !s.active } : s);
    setSchedule(updated);
    onSave({ paymentSchedule: updated });
  };

  const boxStyle = {
    background: 'white', borderRadius: 16, boxShadow: '0 2px 12px rgba(0,0,0,0.07)',
    padding: open ? 20 : 16, marginTop: 16, transition: 'all 0.3s',
  };

  const headerStyle = {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer',
    fontWeight: 700, fontSize: 16, color: '#334155',
  };

  return (
    <div style={boxStyle}>
      <div style={headerStyle} onClick={() => setOpen(o => !o)}>
        <span>💳 每月付款排程 ({schedule.filter(s => s.active).length} 項)</span>
        <span style={{ fontSize: 13, color: '#94a3b8' }}>{open ? '▲ 收起' : '▼ 展開'}</span>
      </div>

      {open && (
        <div style={{ marginTop: 16 }}>
          {/* Schedule Table */}
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid #e2e8f0', textAlign: 'left' }}>
                  <th style={{ padding: '8px 12px' }}>日期</th>
                  <th style={{ padding: '8px 12px' }}>項目</th>
                  <th style={{ padding: '8px 12px' }}>分類</th>
                  <th style={{ padding: '8px 12px' }}>金額</th>
                  <th style={{ padding: '8px 12px' }}>分店/對象</th>
                  <th style={{ padding: '8px 12px' }}>狀態</th>
                  <th style={{ padding: '8px 12px' }}>操作</th>
                </tr>
              </thead>
              <tbody>
                {schedule.sort((a, b) => a.day - b.day).map((item, i) => (
                  <tr key={item.id} style={{ borderBottom: '1px solid #f1f5f9', background: i % 2 ? '#f8fafc' : 'white', opacity: item.active ? 1 : 0.5 }}>
                    <td style={{ padding: '10px 12px', fontWeight: 600 }}>每月 {item.day} 號</td>
                    <td style={{ padding: '10px 12px' }}>{item.label}</td>
                    <td style={{ padding: '10px 12px' }}>
                      <span style={{ background: item.category === '人工' ? '#dbeafe' : item.category === '租金' ? '#fef3c7' : '#f1f5f9', padding: '2px 8px', borderRadius: 12, fontSize: 12 }}>{item.category}</span>
                    </td>
                    <td style={{ padding: '10px 12px' }}>{item.amount ? `$${item.amount.toLocaleString()}` : '—'}</td>
                    <td style={{ padding: '10px 12px', color: '#64748b' }}>{item.store || item.staff || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>
                      <span onClick={() => toggleActive(item.id)} style={{ cursor: 'pointer', background: item.active ? '#dcfce7' : '#fee2e2', color: item.active ? '#16a34a' : '#ef4444', padding: '2px 8px', borderRadius: 12, fontSize: 12 }}>
                        {item.active ? '✓ 啟用' : '✗ 停用'}
                      </span>
                    </td>
                    <td style={{ padding: '10px 12px' }}>
                      <button onClick={() => startEdit(item)} style={{ background: 'none', border: 'none', cursor: 'pointer', marginRight: 8, color: ACCENT }}>✏️</button>
                      <button onClick={() => deleteItem(item.id)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#ef4444' }}>🗑️</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Add/Edit Form */}
          <div style={{ marginTop: 16, padding: 16, background: '#f8fafc', borderRadius: 12, border: '1px solid #e2e8f0' }}>
            <div style={{ fontWeight: 600, marginBottom: 12, fontSize: 14 }}>{editing ? '✏️ 編輯排程' : '➕ 新增排程'}</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12, alignItems: 'flex-end' }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#64748b', marginBottom: 4 }}>項目名稱</label>
                <input value={form.label} onChange={e => setForm(f => ({ ...f, label: e.target.value }))}
                  placeholder="例：太子租金" style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', width: 150 }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#64748b', marginBottom: 4 }}>每月幾號</label>
                <input type="number" min={1} max={31} value={form.day} onChange={e => setForm(f => ({ ...f, day: Number(e.target.value) }))}
                  style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', width: 70 }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#64748b', marginBottom: 4 }}>金額 (HK$)</label>
                <input type="number" value={form.amount} onChange={e => setForm(f => ({ ...f, amount: Number(e.target.value) }))}
                  placeholder="0" style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', width: 100 }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#64748b', marginBottom: 4 }}>分類</label>
                <select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}
                  style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0' }}>
                  {categories.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#64748b', marginBottom: 4 }}>分店/對象</label>
                <input value={form.store || form.staff || ''} onChange={e => setForm(f => ({ ...f, store: e.target.value, staff: e.target.value }))}
                  placeholder="例：太子" style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', width: 120 }} />
              </div>
              <button onClick={saveItem} disabled={!form.label}
                style={{ padding: '8px 20px', borderRadius: 8, background: form.label ? ACCENT : '#cbd5e1', color: 'white', border: 'none', cursor: form.label ? 'pointer' : 'default', fontWeight: 600 }}>
                {editing ? '更新' : '新增'}
              </button>
              {editing && (
                <button onClick={() => { setEditing(null); setForm({ label: '', day: 1, amount: 0, category: '租金', store: '', staff: '', active: true }); }}
                  style={{ padding: '8px 16px', borderRadius: 8, background: '#f1f5f9', color: '#64748b', border: 'none', cursor: 'pointer' }}>
                  取消
                </button>
              )}
            </div>
          </div>

          <div style={{ marginTop: 12, fontSize: 12, color: '#94a3b8' }}>
            💡 提示：排程會自動喺每月指定日期生成任務提醒。你可以隨時新增、修改或停用。
          </div>
        </div>
      )}
    </div>
  );
}
